In [4]:
import numpy as np
import pandas as pd

In [5]:
import pandas as pd

credits = pd.read_csv("tmdb.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [6]:
df.describe()

NameError: name 'df' is not defined

In [7]:
credits.head

<bound method NDFrame.head of       movie_id                                     title  \
0        19995                                    Avatar
1          285  Pirates of the Caribbean: At World's End
2       206647                                   Spectre
3        49026                     The Dark Knight Rises
4        49529                               John Carter
...        ...                                       ...
4798      9367                               El Mariachi
4799     72766                                 Newlyweds
4800    231617                 Signed, Sealed, Delivered
4801    126186                          Shanghai Calling
4802     25975                         My Date with Drew

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4798  [{"cast_id": 1, "character": "El Mariachi", "c...
4799  [{"cast_id": 1, "character": "Buzzy", "credit_...
4800  [{"cast_id": 8, "character": "Oliver O\u2019To...
4801  [{"cast_id": 3, "character": "Sam", "credit_id...
4802  [{"cast_id": 3, "character": "Herself", "credi...

                                                   crew
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4798  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 4 columns]>

In [8]:
movies = movies.merge(credits, on ='title')

In [9]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [11]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [12]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.dropna(inplace = True)

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
import ast 
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
 def convert3 (obj):
     L = []
     counter = 0 
     for i in ast.literal_eval(obj):
         if counter !=3 :
             L.append(i['name'])
         else:
             break
     return L

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i ['job'] == 'Director':
            L.append(i['name'])
            break
            
    return L

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [28]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [30]:
movies['genres'] = movies['genres'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['keywords'] = movies['keywords'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['cast'] = movies['cast'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['crew'] = movies['crew'].apply(lambda x :[i.replace(" ","") for i in x ])

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [32]:
movies['tags'] = movies['keywords']+movies['cast']+movies['crew']+movies['overview']+movies['genres']

In [33]:
new_df = movies[['movie_id','title','tags']]

In [34]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p..."

In [35]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\laksh\AppData\Local\Temp\ipykernel_23212\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\laksh\AppData\Local\Temp\ipykernel_23212\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [39]:
new_df['tags'][1]

"ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley stellanskarsgård chowyun-fat billnighy geoffreyrush jackdavenport kevinmcnally tomhollander naomieharris jonathanpryce keithrichards leearenberg mackenziecrook gregellis davidbailie martinklebba davidschofield laurenmaher vanessabranch angusbarnett gilesnew reggielee dominicscottkay takayofischer davidmeunier ho-kwantse andybeckwith peterdonaldbadalamentiii christophers.capp keithrichards hakeemkae-kazim ghassanmassoud goreverbinski captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action"

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words = 'english')

In [41]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [42]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
len(cv.get_feature_names_out())

5000

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [46]:
def stem (text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))

    return" ".join(y)

In [47]:
ps.stem('dance')

'danc'

In [60]:
sorted(list(enumerate(similarity[0])) ,reverse = True , key=lambda x:x[1])[1:6]

[(1916, np.float32(0.23473825)),
 (1214, np.float32(0.23294541)),
 (582, np.float32(0.2309783)),
 (539, np.float32(0.22528177)),
 (507, np.float32(0.21912524))]

In [49]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\laksh\AppData\Local\Temp\ipykernel_23212\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity = cosine_similarity(vectors)

In [52]:
def recommend (movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)) ,reverse = True , key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [53]:
new_df.iloc[1256].title

'The Impossible'

In [54]:
recommend('Batman')

Batman
Batman & Robin
Batman
Batman Returns
Batman Forever

In [55]:
similarity = similarity.astype("float32")

import pickle
pickle.dump(similarity, open("similarity.pkl", "wb"))

In [56]:
import pickle

In [57]:
 pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [58]:
 pickle.dump(similarity,open('similarity.pkl','wb'))

In [59]:
pip install jupyterlab-git

Requirement already satisfied: jupyterlab-git in c:\users\laksh\anaconda3\lib\site-packages (0.54.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: jupyter-server<3,>=2.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from jupyterlab-git) (2.15.0)
Requirement already satisfied: jupyterlab-git-core>=0.52.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (0.54.0)
Requirement already satisfied: traitlets~=5.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyterlab-git) (5.14.3)
Requirement already satisfied: anyio>=3.1.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (4.7.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (5.7.2)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (7.4.0)
Requirement already satisfied: packaging>=22.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (24.2)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (2.0.15)
Requirement already satisfied: pyzmq>=24 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (26.2.0)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.17.1)
Requirement already satisfied: tornado>=6.2.0 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (6.5.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (1.8.0)
Requirement already satisfied: idna>=2.8 in c:\users\laksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\laksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\laksh\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (21.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\laksh\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.0.1->jupyterlab-git) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.0.1->jupyterlab-git) (308)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (4.23.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (6.0.2)
Requirement already satisfied: referencing in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.30.2)
Requirement already satisfied: rfc3339-validator in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\laksh\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.1.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (2023.7.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.22.3)
Requirement already satisfied: fqdn in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.5.1)
Requirement already satisfied: isoduration in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.1)
Requirement already satisfied: uri-template in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\laksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (25.10.0)
Requirement already satisfied: pexpect in c:\users\laksh\anaconda3\lib\site-packages (from jupyterlab-git-core>=0.52.0->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (4.8.0)
Requirement already satisfied: nbdime~=4.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (4.0.4)
Requirement already satisfied: colorama in c:\users\laksh\anaconda3\lib\site-packages (from nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (0.4.6)
Requirement already satisfied: gitpython!=2.1.4,!=2.1.5,!=2.1.6 in c:\users\laksh\anaconda3\lib\site-packages (from nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (3.1.43)
Requirement already satisfied: pygments in c:\users\laksh\anaconda3\lib\site-packages (from nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (2.19.1)
Requirement already satisfied: requests in c:\users\laksh\anaconda3\lib\site-packages (from nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (2.32.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from gitpython!=2.1.4,!=2.1.5,!=2.1.6->nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=2.1.4,!=2.1.5,!=2.1.6->nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (4.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\laksh\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\laksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.5.0)
Requirement already satisfied: webencodings in c:\users\laksh\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\laksh\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\laksh\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.20.0)
Requirement already satisfied: six>=1.5 in c:\users\laksh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.17.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\laksh\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.17.1)
Requirement already satisfied: pycparser in c:\users\laksh\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.21)
Requirement already satisfied: soupsieve>1.2 in c:\users\laksh\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.5)
Requirement already satisfied: arrow>=0.15.0 in c:\users\laksh\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.3.0)
Requirement already satisfied: ptyprocess>=0.5 in c:\users\laksh\anaconda3\lib\site-packages (from pexpect->jupyterlab-git-core>=0.52.0->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (0.7.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\laksh\anaconda3\lib\site-packages (from requests->nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\laksh\anaconda3\lib\site-packages (from requests->nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\laksh\anaconda3\lib\site-packages (from requests->nbdime~=4.0.1->jupyterlab-git-core[nbdime]>=0.52.0->jupyterlab-git) (2025.10.5)